name: DamageScaling
main: me.BaddCamden.damagescaling.DamageScalingPlugin
version: 1.0.0
author: BaddCamden
description: >
  Visually scale player health while preserving real values on the server and persisting them per-player.
api-version: 1.21.10
commands:
  damagescaling:
    description: Enable or disable the damage scaling visuals.
    usage: /damagescaling <enable|disable>
    permission: damagescaling.admin
permissions:
  damagescaling.admin:
    description: Allows toggling the damage scaling plugin.
    default: op
